### PR TITLE
Add `port` option

### PR DESCRIPTION
**Pull request by arthurvr**
Is this how you'd like to have the `port` option?

Fixes https://github.com/sindresorhus/is-reachable/issues/1

### CODE REVIEW

**Comment by kevva** [comment]
How does that work for multiple hostnames with different ports?

**Comment by arthurvr** [comment]
Ugh. It does not. It just takes the same port always. If there would have been a test for the behavior with multiple hostnames, I would've catched that :wink: 

How would we like it to look like, then? All in the hostname string? Let all hostnames be objects?

**Comment by sindresorhus** [comment]
Supporting `website.com:80` is ok I think.

**Comment by silverwind** [comment]
`host:80` seems reasonable, thought maybe a bit clumsy. How about dropping array support and going with the option object (with a typecheck for `number`).

**Comment by sindresorhus** [comment]
Don't you think array support is useful? We make use of it in `is-online`.

**Comment by arthurvr** [comment]
> Supporting website.com:80 is ok I think.

Hmm wouldn't that be confusing in some way. It's not a url, it's a hostname. We would end up with a bunch of string magic, both to parse something like that and to generate a string like this. It's not a URL, we can't just `url.parse()` it.

the other solution I see is something like this:

```js
isReachable([{
     hostname: 'arthurverschaeve.be',
     port: 80
}, {
     hostname: 'sindresorhus.com',
     port: 80
}], function (err, reachable) {
     // things
});
```

But I don't really like that too. It's pretty verbose, and I guess 95% of the use cases for this module use port 80 anyways.

> Don't you think array support is useful?

Unsure. I rarely use it but the `is-online` use case is pretty valid.

**Comment by silverwind** [comment]
> Don't you think array support is useful?

It is. Given that the async stuff is non-trivial, I'd say we should keep it.

> We would end up with a bunch of string magic

I'd say go for `host:port`, it seems the simplest way. You could parse it through a [regex](
https://github.com/silverwind/tcpie/blob/e898a5a7a9f1fd67aa6da3f33ccdf04ab0cf24fe/tcpie.js#L69-L73).

If you're fancy, you could even add full URL support (could use something like [port-numbers](https://github.com/silverwind/port-numbers) to obtain the numerical port fort the protocol to support things like `ftp://`, `https://`, etc).

**Comment by sindresorhus** [comment]
> Hmm wouldn't that be confusing in some way. It's not a url, it's a hostname.

The term for `hostname` + `port` in node is `host`, so I guess we could just change it to that in the docs.

https://nodejs.org/docs/latest/api/url.html

> I'd say go for host:port, it seems the simplest way. You could parse it through a regex.

Yes, let's go with that. I doubt it's going to be used a lot anyways. Regex seems excessive. Couldn't you just `host.split(':')`?

> If you're fancy, you could even add full URL support

I think that's too much tbh.

**Comment by silverwind** [comment]
> Couldn't you just `host.split(':')`

Yeah that would work too, as `:` is invalid in an hostname. Let's do that.

**Comment by sindresorhus** [comment]
ping @arthurvr :)

**Comment by silverwind** [comment]
@arthurvr you *might* want to rewrite this PR with the latest changes. Sorry about that :wink:.

**Comment by silverwind** [comment]
Also to consider here: there is undocumented support for ip adresses instead of hostnames, and I'd eventually document that too. The result of adress support is that you unfortunately can't simply do `split(':')` anymore because of the IPv6 host:port syntax. Here's a few examples of what we should support:

```
hostname
hostname:80
1.2.3.4
1.2.3.4:80
2001:db8::
[2001:db8::]:80
```

There's probably an npm module around to handle this parsing. Maybe even `url` could be of some help here.

**Comment by sindresorhus** [comment]
> There's probably an npm module around to handle this parsing. Maybe even url could be of some help.

There is now: https://github.com/sindresorhus/url-parse-lax

`url.parse()` can't handle protocol-less URLs/IPs.

**Comment by silverwind** [comment]
@sindresorhus :heart:

**Comment by arthurvr** [comment]
Sorry for the delay. I'll take care of this soon :)

**Comment by kevva** [comment]
Goodie :).

**Comment by sindresorhus** [comment]
ping @arthurvr :)

**Comment by arthurvr** [comment]
Updated.

**Comment by silverwind** [comment]
lgtm!

**Comment by sindresorhus** [comment]
Thanks @arthurvr :)

**Pull request closed without merging**
