### PR TITLE
Update index.js

### LINKED ISSUE #28: TypeError: Cannot read property 'port' of null
https://runkit.com/indatawetrust/5b7abc789afb450012967b6d

screen shot 2018-08-20 at 16 05 21

### PR DESCRIPTION
**Pull request by indatawetrust**
Fixes #28

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you add a test?

**Comment by sindresorhus** [comment]
Also give the PR a proper title.

**Comment by sindresorhus** [comment]
Ping :)

**Comment by sindresorhus** [comment]
Closing as this PR is empty.

**Comment by indatawetrust** [comment]
I do not receive this error with the latest version.

**Pull request closed without merging**
