### PR TITLE
Add support for optional protocol and port in the browser version

### PR DESCRIPTION
**Pull request by danielmahon**
Introduced to fix https://github.com/sindresorhus/is-online/issues/37

### CODE REVIEW

**Comment by tnightingale** [comment]
This breaks support for protocol-relative urls as url-parse-lax doesn't parse hostname out of them:

``` javascript
var parse = require('url-parse-lax');
console.log(parse('//google.com'));
// Output:
{
	"protocol": null,
	"slashes": null,
	"auth": null,
	"host": null,
	"port": null,
	"hostname": null,
	"hash": null,
	"search": null,
	"query": null,
	"pathname": "//google.com",
	"path": "//google.com",
	"href": "//google.com"
}
```

**Comment by tnightingale** [comment]
Ah I hadn't seen that update, makes sense. Thanks!

**Comment by danielmahon** [comment]
@tnightingale It only breaks if you add the `//` (which broke before as well I think as the `//` are hard-coded) if you leave out the protocol it defaults to protocol-relative URL. `google.com => //google.com`

**Comment by sindresorhus** [comment]
You can leave out the protocol completely (that's not called protocol-relative URL btw). It will just default to `http://`.

**Pull request merged**
