### PR TITLE
Add test for parked domain

### PR DESCRIPTION
**Pull request by AleksandrHovhannisyan**
Currently failing test for a parked domain, as requested in #40:

image

### CODE REVIEW

**Comment by sindresorhus** [comment]
Seems like the test is passing on Travis: https://travis-ci.org/sindresorhus/is-reachable/jobs/631579229?utm_medium=notification&utm_source=github_status

**Comment by AleksandrHovhannisyan** [comment]
Interesting... So it's just failing locally? What about on your end?

**Comment by sindresorhus** [comment]
The test succeeds locally for me.

**Comment by sindresorhus** [comment]
Then I don't really know what the issue is.

**Pull request closed without merging**
